'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WsBDCC
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WsSincronoSoap", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class WsSincrono
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultaCpfOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaRenavamOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaCrachaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistraEntradaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private VerificacaoSGBDCCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ListaAcessosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaCpfIntranetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaCNPJIntranetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaEmpresaPorCnpjOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.AgendamentoCargaSoltaSGIPA.My.MySettings.Default.AgendamentoCargaSoltaSGIPA_WsBDCC_WsSincrono
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultaCpfCompleted As ConsultaCpfCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaRenavamCompleted As ConsultaRenavamCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaCrachaCompleted As ConsultaCrachaCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistraEntradaCompleted As RegistraEntradaCompletedEventHandler
        
        '''<remarks/>
        Public Event VerificacaoSGBDCCCompleted As VerificacaoSGBDCCCompletedEventHandler
        
        '''<remarks/>
        Public Event ListaAcessosCompleted As ListaAcessosCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaCpfIntranetCompleted As ConsultaCpfIntranetCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaCNPJIntranetCompleted As ConsultaCNPJIntranetCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaEmpresaPorCnpjCompleted As ConsultaEmpresaPorCnpjCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/ConsultaCpf", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaCpf(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer, ByVal cnpj As String, ByVal autonomo As Integer) As TecondiBdccResponse
            Dim results() As Object = Me.Invoke("ConsultaCpf", New Object() {cpf, registraEntradaSemCracha, cnpj, autonomo})
            Return CType(results(0),TecondiBdccResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaCpfAsync(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer, ByVal cnpj As String, ByVal autonomo As Integer)
            Me.ConsultaCpfAsync(cpf, registraEntradaSemCracha, cnpj, autonomo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaCpfAsync(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer, ByVal cnpj As String, ByVal autonomo As Integer, ByVal userState As Object)
            If (Me.ConsultaCpfOperationCompleted Is Nothing) Then
                Me.ConsultaCpfOperationCompleted = AddressOf Me.OnConsultaCpfOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCpf", New Object() {cpf, registraEntradaSemCracha, cnpj, autonomo}, Me.ConsultaCpfOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaCpfOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCpfCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCpfCompleted(Me, New ConsultaCpfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/ConsultaRenavam", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaRenavam(ByVal renavam As String, ByVal registraEntradaSemCracha As Integer) As TecondiBdccResponse
            Dim results() As Object = Me.Invoke("ConsultaRenavam", New Object() {renavam, registraEntradaSemCracha})
            Return CType(results(0),TecondiBdccResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaRenavamAsync(ByVal renavam As String, ByVal registraEntradaSemCracha As Integer)
            Me.ConsultaRenavamAsync(renavam, registraEntradaSemCracha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaRenavamAsync(ByVal renavam As String, ByVal registraEntradaSemCracha As Integer, ByVal userState As Object)
            If (Me.ConsultaRenavamOperationCompleted Is Nothing) Then
                Me.ConsultaRenavamOperationCompleted = AddressOf Me.OnConsultaRenavamOperationCompleted
            End If
            Me.InvokeAsync("ConsultaRenavam", New Object() {renavam, registraEntradaSemCracha}, Me.ConsultaRenavamOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaRenavamOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaRenavamCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaRenavamCompleted(Me, New ConsultaRenavamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/ConsultaCracha", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaCracha(ByVal cracha As String) As TecondiBdccCrachaResponse
            Dim results() As Object = Me.Invoke("ConsultaCracha", New Object() {cracha})
            Return CType(results(0),TecondiBdccCrachaResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaCrachaAsync(ByVal cracha As String)
            Me.ConsultaCrachaAsync(cracha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaCrachaAsync(ByVal cracha As String, ByVal userState As Object)
            If (Me.ConsultaCrachaOperationCompleted Is Nothing) Then
                Me.ConsultaCrachaOperationCompleted = AddressOf Me.OnConsultaCrachaOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCracha", New Object() {cracha}, Me.ConsultaCrachaOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaCrachaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCrachaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCrachaCompleted(Me, New ConsultaCrachaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/RegistraEntrada", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub RegistraEntrada(ByVal numeroCracha As String, ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal local As String, ByVal usuarioLogado As String, ByVal ip As String)
            Me.Invoke("RegistraEntrada", New Object() {numeroCracha, tipoDocumento, numeroDocumento, local, usuarioLogado, ip})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistraEntradaAsync(ByVal numeroCracha As String, ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal local As String, ByVal usuarioLogado As String, ByVal ip As String)
            Me.RegistraEntradaAsync(numeroCracha, tipoDocumento, numeroDocumento, local, usuarioLogado, ip, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistraEntradaAsync(ByVal numeroCracha As String, ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal local As String, ByVal usuarioLogado As String, ByVal ip As String, ByVal userState As Object)
            If (Me.RegistraEntradaOperationCompleted Is Nothing) Then
                Me.RegistraEntradaOperationCompleted = AddressOf Me.OnRegistraEntradaOperationCompleted
            End If
            Me.InvokeAsync("RegistraEntrada", New Object() {numeroCracha, tipoDocumento, numeroDocumento, local, usuarioLogado, ip}, Me.RegistraEntradaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistraEntradaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistraEntradaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistraEntradaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/VerificacaoSGBDCC", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VerificacaoSGBDCC() As String
            Dim results() As Object = Me.Invoke("VerificacaoSGBDCC", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VerificacaoSGBDCCAsync()
            Me.VerificacaoSGBDCCAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VerificacaoSGBDCCAsync(ByVal userState As Object)
            If (Me.VerificacaoSGBDCCOperationCompleted Is Nothing) Then
                Me.VerificacaoSGBDCCOperationCompleted = AddressOf Me.OnVerificacaoSGBDCCOperationCompleted
            End If
            Me.InvokeAsync("VerificacaoSGBDCC", New Object(-1) {}, Me.VerificacaoSGBDCCOperationCompleted, userState)
        End Sub
        
        Private Sub OnVerificacaoSGBDCCOperationCompleted(ByVal arg As Object)
            If (Not (Me.VerificacaoSGBDCCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VerificacaoSGBDCCCompleted(Me, New VerificacaoSGBDCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/ListaAcessos", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ListaAcessos(ByVal dataInicial As String, ByVal dataFinal As String, ByVal local As String) As BdccAcesso()
            Dim results() As Object = Me.Invoke("ListaAcessos", New Object() {dataInicial, dataFinal, local})
            Return CType(results(0),BdccAcesso())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ListaAcessosAsync(ByVal dataInicial As String, ByVal dataFinal As String, ByVal local As String)
            Me.ListaAcessosAsync(dataInicial, dataFinal, local, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ListaAcessosAsync(ByVal dataInicial As String, ByVal dataFinal As String, ByVal local As String, ByVal userState As Object)
            If (Me.ListaAcessosOperationCompleted Is Nothing) Then
                Me.ListaAcessosOperationCompleted = AddressOf Me.OnListaAcessosOperationCompleted
            End If
            Me.InvokeAsync("ListaAcessos", New Object() {dataInicial, dataFinal, local}, Me.ListaAcessosOperationCompleted, userState)
        End Sub
        
        Private Sub OnListaAcessosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ListaAcessosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ListaAcessosCompleted(Me, New ListaAcessosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/ConsultaCpfIntranet", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaCpfIntranet(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer) As TecondiBdccResponse
            Dim results() As Object = Me.Invoke("ConsultaCpfIntranet", New Object() {cpf, registraEntradaSemCracha})
            Return CType(results(0),TecondiBdccResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaCpfIntranetAsync(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer)
            Me.ConsultaCpfIntranetAsync(cpf, registraEntradaSemCracha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaCpfIntranetAsync(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer, ByVal userState As Object)
            If (Me.ConsultaCpfIntranetOperationCompleted Is Nothing) Then
                Me.ConsultaCpfIntranetOperationCompleted = AddressOf Me.OnConsultaCpfIntranetOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCpfIntranet", New Object() {cpf, registraEntradaSemCracha}, Me.ConsultaCpfIntranetOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaCpfIntranetOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCpfIntranetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCpfIntranetCompleted(Me, New ConsultaCpfIntranetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/ConsultaCNPJIntranet", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaCNPJIntranet(ByVal cnpj As String, ByVal autonomo As Integer) As TecondiBdccResponse
            Dim results() As Object = Me.Invoke("ConsultaCNPJIntranet", New Object() {cnpj, autonomo})
            Return CType(results(0),TecondiBdccResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaCNPJIntranetAsync(ByVal cnpj As String, ByVal autonomo As Integer)
            Me.ConsultaCNPJIntranetAsync(cnpj, autonomo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaCNPJIntranetAsync(ByVal cnpj As String, ByVal autonomo As Integer, ByVal userState As Object)
            If (Me.ConsultaCNPJIntranetOperationCompleted Is Nothing) Then
                Me.ConsultaCNPJIntranetOperationCompleted = AddressOf Me.OnConsultaCNPJIntranetOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCNPJIntranet", New Object() {cnpj, autonomo}, Me.ConsultaCNPJIntranetOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaCNPJIntranetOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCNPJIntranetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCNPJIntranetCompleted(Me, New ConsultaCNPJIntranetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tecondi.com.br/services/TecondiBdccWs/ConsultaEmpresaPorCnpj", RequestNamespace:="http://tecondi.com.br/services/TecondiBdccWs", ResponseNamespace:="http://tecondi.com.br/services/TecondiBdccWs", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaEmpresaPorCnpj(ByVal cnpj As String) As BdccCnpjEmpresa
            Dim results() As Object = Me.Invoke("ConsultaEmpresaPorCnpj", New Object() {cnpj})
            Return CType(results(0),BdccCnpjEmpresa)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaEmpresaPorCnpjAsync(ByVal cnpj As String)
            Me.ConsultaEmpresaPorCnpjAsync(cnpj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaEmpresaPorCnpjAsync(ByVal cnpj As String, ByVal userState As Object)
            If (Me.ConsultaEmpresaPorCnpjOperationCompleted Is Nothing) Then
                Me.ConsultaEmpresaPorCnpjOperationCompleted = AddressOf Me.OnConsultaEmpresaPorCnpjOperationCompleted
            End If
            Me.InvokeAsync("ConsultaEmpresaPorCnpj", New Object() {cnpj}, Me.ConsultaEmpresaPorCnpjOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaEmpresaPorCnpjOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaEmpresaPorCnpjCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaEmpresaPorCnpjCompleted(Me, New ConsultaEmpresaPorCnpjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class TecondiBdccResponse
        
        Private codigoRetornoField As String
        
        Private descricaoRetornoField As String
        
        '''<remarks/>
        Public Property CodigoRetorno() As String
            Get
                Return Me.codigoRetornoField
            End Get
            Set
                Me.codigoRetornoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescricaoRetorno() As String
            Get
                Return Me.descricaoRetornoField
            End Get
            Set
                Me.descricaoRetornoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class BdccCnpjEmpresa
        
        Private cnpjField As String
        
        Private nomeField As String
        
        Private situacaoField As String
        
        '''<remarks/>
        Public Property Cnpj() As String
            Get
                Return Me.cnpjField
            End Get
            Set
                Me.cnpjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Situacao() As String
            Get
                Return Me.situacaoField
            End Get
            Set
                Me.situacaoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class BdccAcesso
        
        Private numeroCrachaField As String
        
        Private tipoDocumentoField As String
        
        Private numeroDocumentoField As String
        
        Private dataAcessoField As Date
        
        Private localizacaoField As String
        
        Private usuarioLogadoField As String
        
        Private ipField As String
        
        '''<remarks/>
        Public Property NumeroCracha() As String
            Get
                Return Me.numeroCrachaField
            End Get
            Set
                Me.numeroCrachaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataAcesso() As Date
            Get
                Return Me.dataAcessoField
            End Get
            Set
                Me.dataAcessoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Localizacao() As String
            Get
                Return Me.localizacaoField
            End Get
            Set
                Me.localizacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UsuarioLogado() As String
            Get
                Return Me.usuarioLogadoField
            End Get
            Set
                Me.usuarioLogadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ip() As String
            Get
                Return Me.ipField
            End Get
            Set
                Me.ipField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class TecondiBdccCrachaResponse
        
        Private codigoRetornoField As String
        
        Private descricaoRetornoField As String
        
        Private codigoCrachaField As String
        
        Private situacaoCrachaField As String
        
        '''<remarks/>
        Public Property CodigoRetorno() As String
            Get
                Return Me.codigoRetornoField
            End Get
            Set
                Me.codigoRetornoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescricaoRetorno() As String
            Get
                Return Me.descricaoRetornoField
            End Get
            Set
                Me.descricaoRetornoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoCracha() As String
            Get
                Return Me.codigoCrachaField
            End Get
            Set
                Me.codigoCrachaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SituacaoCracha() As String
            Get
                Return Me.situacaoCrachaField
            End Get
            Set
                Me.situacaoCrachaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ConsultaCpfCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCpfCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaCpfCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TecondiBdccResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TecondiBdccResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ConsultaRenavamCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaRenavamCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaRenavamCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TecondiBdccResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TecondiBdccResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ConsultaCrachaCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCrachaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaCrachaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TecondiBdccCrachaResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TecondiBdccCrachaResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub RegistraEntradaCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub VerificacaoSGBDCCCompletedEventHandler(ByVal sender As Object, ByVal e As VerificacaoSGBDCCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VerificacaoSGBDCCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ListaAcessosCompletedEventHandler(ByVal sender As Object, ByVal e As ListaAcessosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ListaAcessosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BdccAcesso()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BdccAcesso())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ConsultaCpfIntranetCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCpfIntranetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaCpfIntranetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TecondiBdccResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TecondiBdccResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ConsultaCNPJIntranetCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCNPJIntranetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaCNPJIntranetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TecondiBdccResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TecondiBdccResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub ConsultaEmpresaPorCnpjCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaEmpresaPorCnpjCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaEmpresaPorCnpjCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BdccCnpjEmpresa
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BdccCnpjEmpresa)
            End Get
        End Property
    End Class
End Namespace
