'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AgendarCS

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSair As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtReserva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReserva As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSemSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSemSaldo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNavio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNavio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblViagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViagem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExportador As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeadLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeadLine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblM3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblM3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUtilizados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUtilizados As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPesoBruto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPesoBruto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDisponiveis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisponiveis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVolumes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVolumes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMotorista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotorista As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbCavalo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCavalo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTransportadora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransportadora As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbCarreta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCarreta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''msgErroNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgErroNF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgSalvar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtArquivoDanfe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArquivoDanfe As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnUploadNota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploadNota As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtXml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtXml As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''msgSucessoDanfe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgSucessoDanfe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDANFE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDANFE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSerie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmissor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmissor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''xCNPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xCNPJ As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xNome As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xFant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xFant As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xLgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xLgr As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''nro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nro As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xBairro As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xMun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xMun As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xUF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xUF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xCEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xCEP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xPais As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xFone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xFone As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xIE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xIE As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''xIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xIM As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtEmissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmissao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQtde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoBruto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoBruto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtM3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSalvarNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarNF As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelarNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelarNF As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConcluirNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConcluirNF As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dgConsultaNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgConsultaNF As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtCNPJResponsavel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNPJResponsavel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hiddenText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenText As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenTextCNPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenTextCNPJ As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtEmailResponsavel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailResponsavel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnGrid As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dgConsultaPeriodos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgConsultaPeriodos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblCodigoPatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoPatio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoAgendamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoAgendamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoBooking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoBooking As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoMotorista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoMotorista As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoVeiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoVeiculo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoProtocolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoProtocolo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoNF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoPeriodo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQuantidadeSelecionadaNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuantidadeSelecionadaNF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblM3SelecionadaNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblM3SelecionadaNF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPesoSelecionadaNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPesoSelecionadaNF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblResp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblResp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Lblidcnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lblidcnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AccordionIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccordionIndex As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAuxiliar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAuxiliar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpePergunta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePergunta As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPergunta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPergunta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnNao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNao As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSim As Global.System.Web.UI.WebControls.Button
End Class
