'------------------------------------------------------------------------------
<<<<<<< HEAD
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
=======
' <gerado automaticamente>
'     Este código foi gerado por uma ferramenta.
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for recriado
' </gerado automaticamente>
>>>>>>> dev-kleiton
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CadastrarAgendamentos

    '''<summary>
<<<<<<< HEAD
    '''PanelForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle PanelForm.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents PanelForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
<<<<<<< HEAD
    '''form2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle form2.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
<<<<<<< HEAD
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle ScriptManager1.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
<<<<<<< HEAD
    '''pnlMsgErro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle pnlMsgErro.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents pnlMsgErro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
<<<<<<< HEAD
    '''lblMsgErro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle lblMsgErro.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents lblMsgErro As Global.System.Web.UI.WebControls.Label

    '''<summary>
<<<<<<< HEAD
    '''txtNomeMotorista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtNomeMotorista.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtNomeMotorista As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''cbCNH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbCNH.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbCNH As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
<<<<<<< HEAD
    '''cbCNH_ListSearchExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbCNH_ListSearchExtender.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbCNH_ListSearchExtender As Global.AjaxControlToolkit.ListSearchExtender

    '''<summary>
<<<<<<< HEAD
    '''cbCavalo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbCavalo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbCavalo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
<<<<<<< HEAD
    '''cbCavalo_ListSearchExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbCavalo_ListSearchExtender.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbCavalo_ListSearchExtender As Global.AjaxControlToolkit.ListSearchExtender

    '''<summary>
<<<<<<< HEAD
    '''hddnCbCavaloCarreta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnCbCavaloCarreta As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cbCarreta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbCarreta.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbCarreta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
<<<<<<< HEAD
    '''cbCarreta_ListSearchExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbCarreta_ListSearchExtender.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbCarreta_ListSearchExtender As Global.AjaxControlToolkit.ListSearchExtender

    '''<summary>
<<<<<<< HEAD
    '''txtTara control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtTara.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtTara As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''txtChassi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtChassi.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtChassi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''CheckAutonomo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle CheckAutonomo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents CheckAutonomo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
<<<<<<< HEAD
    '''txtTransportadora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtTransportadora.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtTransportadora As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''lblPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle lblPeriodo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents lblPeriodo As Global.System.Web.UI.WebControls.Label

    '''<summary>
<<<<<<< HEAD
    '''lblProtocolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle lblProtocolo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents lblProtocolo As Global.System.Web.UI.WebControls.Label

    '''<summary>
<<<<<<< HEAD
    '''lblID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle lblID.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents lblID As Global.System.Web.UI.WebControls.Label

    '''<summary>
<<<<<<< HEAD
    '''btNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle btNovo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents btNovo As Global.System.Web.UI.WebControls.Button

    '''<summary>
<<<<<<< HEAD
    '''btSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle btSalvar.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents btSalvar As Global.System.Web.UI.WebControls.Button

    '''<summary>
<<<<<<< HEAD
    '''btExcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle btExcluir.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents btExcluir As Global.System.Web.UI.WebControls.Button

    '''<summary>
<<<<<<< HEAD
    '''cbTipoDocSaida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbTipoDocSaida.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbTipoDocSaida As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
<<<<<<< HEAD
    '''txtSerieDocSaida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtSerieDocSaida.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtSerieDocSaida As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''txtNrDocSaida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtNrDocSaida.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtNrDocSaida As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''txtEmissaoDocSaida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtEmissaoDocSaida.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtEmissaoDocSaida As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''cbLote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbLote.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbLote As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
<<<<<<< HEAD
    '''txtNotaFiscal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtNotaFiscal.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtNotaFiscal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''txtSerie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtSerie.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtSerie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''txtDataEmissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtDataEmissao.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtDataEmissao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''cbItensCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle cbItensCS.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents cbItensCS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
<<<<<<< HEAD
    '''txtQtde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtQtde.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtQtde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''txtPackingList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle txtPackingList.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents txtPackingList As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''btnExcluirProduto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle btnExcluirProduto.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents btnExcluirProduto As Global.System.Web.UI.WebControls.Button

    '''<summary>
<<<<<<< HEAD
    '''btnAdicProduto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle btnAdicProduto.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents btnAdicProduto As Global.System.Web.UI.WebControls.Button

    '''<summary>
<<<<<<< HEAD
    '''PanelPatioInvalido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle PanelPatioInvalido.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents PanelPatioInvalido As Global.System.Web.UI.WebControls.Panel

    '''<summary>
<<<<<<< HEAD
    '''lblPatioInvalido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle lblPatioInvalido.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents lblPatioInvalido As Global.System.Web.UI.WebControls.Label

    '''<summary>
<<<<<<< HEAD
    '''PanelScrollNotas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle PanelScrollNotas.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents PanelScrollNotas As Global.System.Web.UI.WebControls.Panel

    '''<summary>
<<<<<<< HEAD
    '''dgNotas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle dgNotas.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents dgNotas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
<<<<<<< HEAD
    '''PanelScrollPeriodos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle PanelScrollPeriodos.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents PanelScrollPeriodos As Global.System.Web.UI.WebControls.Panel

    '''<summary>
<<<<<<< HEAD
    '''dgPeriodos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle dgPeriodos.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents dgPeriodos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
<<<<<<< HEAD
    '''lblCodigoPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle lblCodigoPeriodo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents lblCodigoPeriodo As Global.System.Web.UI.WebControls.Label

    '''<summary>
<<<<<<< HEAD
    '''frameDocumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle frameDocumentos.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents frameDocumentos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
<<<<<<< HEAD
    '''frameEmails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle frameEmails.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents frameEmails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
<<<<<<< HEAD
    '''pnLegenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle pnLegenda.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents pnLegenda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
<<<<<<< HEAD
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle Label2.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
<<<<<<< HEAD
    '''lblLoteSelecionado1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle lblLoteSelecionado1.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents lblLoteSelecionado1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
<<<<<<< HEAD
    '''lblPatio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
=======
    '''Controle lblPatio.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
>>>>>>> dev-kleiton
    '''</remarks>
    Protected WithEvents lblPatio As Global.System.Web.UI.WebControls.Label
End Class
