CREATE TABLE SGIPA.TB_AG_CS
(
    AUTONUM                 NUMBER NOT NULL PRIMARY KEY,
    AUTONUM_MOTORISTA       NUMBER NOT NULL,
    EMISSAO_DOC_SAIDA       DATE,
    SERIE_DOC_SAIDA         VARCHAR2(50),
    TIPO_DOC_SAIDA          VARCHAR2(50),
    NUM_DOC_SAIDA           VARCHAR2(50),
    IMPRESSO                NUMBER(1) NOT NULL,
    STATUS                  NUMBER(1) NOT NULL, 
    ANO_PROTOCOLO           NUMBER(4) NOT NULL,
    NUM_PROTOCOLO           NUMBER NOT NULL,
    AUTONUM_GD_RESERVA      NUMBER NOT NULL,
    AUTONUM_TRANSPORTADORA  NUMBER NOT NULL,
    AUTONUM_VEICULO         NUMBER NOT NULL
);
                  
            
CREATE TABLE SGIPA.TB_AG_CS_ITENS
(
    AUTONUM              NUMBER NOT NULL PRIMARY KEY,
    AUTONUM_AGENDAMENTO  NUMBER NOT NULL,
    AUTONUM_NF           NUMBER NOT NULL,
    LOTE                 NUMBER NOT NULL,  
    QTDE                 NUMBER NOT NULL,
    AUTONUM_CS           NUMBER NOT NULL
);

CREATE TABLE SGIPA.TB_AG_CS_NF
(
    AUTONUM              NUMBER NOT NULL PRIMARY KEY,
    NOTAFISCAL           NUMBER NOT NULL,
    SERIE                VARCHAR2(4),
    EMISSAO              DATE,
    LOTE                 NUMBER,  
    AUTONUM_AGENDAMENTO  NUMBER NOT NULL
);

CREATE SEQUENCE SGIPA.SEQ_AG_CS_PROT_2012
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE SGIPA.SEQ_TB_AG_CS
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE SGIPA.SEQ_AG_CS_ITENS
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE SGIPA.SEQ_AG_CS_NF
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE SGIPA.TB_CARGA_SOLTA ADD ("DT_FIM_PERIODO" DATE);
ALTER TABLE SGIPA.TB_BL ADD ("DT_AGENDA_SAIDA" DATE);
ALTER TABLE SGIPA.TB_AGENDAMENTO_POSICAO ADD ("LOTE" NUMBER);