'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WsCraft
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ConexaoMBSoap", [Namespace]:="http://eprofesseonal.com/")>  _
    Partial Public Class ConexaoMB
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RetornaTabelaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExcluirOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExecutarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExecutarScalarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ApontadorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RetornaDadosReservaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RoutingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BloqueadoSNOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ContainerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.AgendamentoREDEX.My.MySettings.Default.AgendamentoREDEX_WsCraft_ConexaoMB
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RetornaTabelaCompleted As RetornaTabelaCompletedEventHandler
        
        '''<remarks/>
        Public Event ExcluirCompleted As ExcluirCompletedEventHandler
        
        '''<remarks/>
        Public Event ExecutarCompleted As ExecutarCompletedEventHandler
        
        '''<remarks/>
        Public Event ExecutarScalarCompleted As ExecutarScalarCompletedEventHandler
        
        '''<remarks/>
        Public Event ApontadorCompleted As ApontadorCompletedEventHandler
        
        '''<remarks/>
        Public Event RetornaDadosReservaCompleted As RetornaDadosReservaCompletedEventHandler
        
        '''<remarks/>
        Public Event RoutingCompleted As RoutingCompletedEventHandler
        
        '''<remarks/>
        Public Event BloqueadoSNCompleted As BloqueadoSNCompletedEventHandler
        
        '''<remarks/>
        Public Event ContainerCompleted As ContainerCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/RetornaTabela", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetornaTabela(ByVal sql As String, ByVal obj As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RetornaTabela", New Object() {sql, obj})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RetornaTabelaAsync(ByVal sql As String, ByVal obj As String)
            Me.RetornaTabelaAsync(sql, obj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RetornaTabelaAsync(ByVal sql As String, ByVal obj As String, ByVal userState As Object)
            If (Me.RetornaTabelaOperationCompleted Is Nothing) Then
                Me.RetornaTabelaOperationCompleted = AddressOf Me.OnRetornaTabelaOperationCompleted
            End If
            Me.InvokeAsync("RetornaTabela", New Object() {sql, obj}, Me.RetornaTabelaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRetornaTabelaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RetornaTabelaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RetornaTabelaCompleted(Me, New RetornaTabelaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/Excluir", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Excluir(ByVal sql As String, ByVal obj As String) As Boolean
            Dim results() As Object = Me.Invoke("Excluir", New Object() {sql, obj})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExcluirAsync(ByVal sql As String, ByVal obj As String)
            Me.ExcluirAsync(sql, obj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExcluirAsync(ByVal sql As String, ByVal obj As String, ByVal userState As Object)
            If (Me.ExcluirOperationCompleted Is Nothing) Then
                Me.ExcluirOperationCompleted = AddressOf Me.OnExcluirOperationCompleted
            End If
            Me.InvokeAsync("Excluir", New Object() {sql, obj}, Me.ExcluirOperationCompleted, userState)
        End Sub
        
        Private Sub OnExcluirOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExcluirCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExcluirCompleted(Me, New ExcluirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/Executar", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Executar(ByVal sql As String, ByVal obj As String) As Boolean
            Dim results() As Object = Me.Invoke("Executar", New Object() {sql, obj})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecutarAsync(ByVal sql As String, ByVal obj As String)
            Me.ExecutarAsync(sql, obj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecutarAsync(ByVal sql As String, ByVal obj As String, ByVal userState As Object)
            If (Me.ExecutarOperationCompleted Is Nothing) Then
                Me.ExecutarOperationCompleted = AddressOf Me.OnExecutarOperationCompleted
            End If
            Me.InvokeAsync("Executar", New Object() {sql, obj}, Me.ExecutarOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecutarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecutarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecutarCompleted(Me, New ExecutarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/ExecutarScalar", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExecutarScalar(ByVal sql As String, ByVal obj As String) As Object
            Dim results() As Object = Me.Invoke("ExecutarScalar", New Object() {sql, obj})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExecutarScalarAsync(ByVal sql As String, ByVal obj As String)
            Me.ExecutarScalarAsync(sql, obj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExecutarScalarAsync(ByVal sql As String, ByVal obj As String, ByVal userState As Object)
            If (Me.ExecutarScalarOperationCompleted Is Nothing) Then
                Me.ExecutarScalarOperationCompleted = AddressOf Me.OnExecutarScalarOperationCompleted
            End If
            Me.InvokeAsync("ExecutarScalar", New Object() {sql, obj}, Me.ExecutarScalarOperationCompleted, userState)
        End Sub
        
        Private Sub OnExecutarScalarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExecutarScalarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExecutarScalarCompleted(Me, New ExecutarScalarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/Apontador", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Apontador(ByVal sql As String, ByVal obj As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Apontador", New Object() {sql, obj})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ApontadorAsync(ByVal sql As String, ByVal obj As String)
            Me.ApontadorAsync(sql, obj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ApontadorAsync(ByVal sql As String, ByVal obj As String, ByVal userState As Object)
            If (Me.ApontadorOperationCompleted Is Nothing) Then
                Me.ApontadorOperationCompleted = AddressOf Me.OnApontadorOperationCompleted
            End If
            Me.InvokeAsync("Apontador", New Object() {sql, obj}, Me.ApontadorOperationCompleted, userState)
        End Sub
        
        Private Sub OnApontadorOperationCompleted(ByVal arg As Object)
            If (Not (Me.ApontadorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ApontadorCompleted(Me, New ApontadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/RetornaDadosReserva", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetornaDadosReserva(ByVal reserva As String, ByVal strusuario As String, ByVal strsenha As String) As clsDadosIntegracao
            Dim results() As Object = Me.Invoke("RetornaDadosReserva", New Object() {reserva, strusuario, strsenha})
            Return CType(results(0),clsDadosIntegracao)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RetornaDadosReservaAsync(ByVal reserva As String, ByVal strusuario As String, ByVal strsenha As String)
            Me.RetornaDadosReservaAsync(reserva, strusuario, strsenha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RetornaDadosReservaAsync(ByVal reserva As String, ByVal strusuario As String, ByVal strsenha As String, ByVal userState As Object)
            If (Me.RetornaDadosReservaOperationCompleted Is Nothing) Then
                Me.RetornaDadosReservaOperationCompleted = AddressOf Me.OnRetornaDadosReservaOperationCompleted
            End If
            Me.InvokeAsync("RetornaDadosReserva", New Object() {reserva, strusuario, strsenha}, Me.RetornaDadosReservaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRetornaDadosReservaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RetornaDadosReservaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RetornaDadosReservaCompleted(Me, New RetornaDadosReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/Routing", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Routing(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String) As clsDadosIntegracaoImp
            Dim results() As Object = Me.Invoke("Routing", New Object() {bl, ceMercante, RaizCnpj, strusuario, strsenha})
            Return CType(results(0),clsDadosIntegracaoImp)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RoutingAsync(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String)
            Me.RoutingAsync(bl, ceMercante, RaizCnpj, strusuario, strsenha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RoutingAsync(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String, ByVal userState As Object)
            If (Me.RoutingOperationCompleted Is Nothing) Then
                Me.RoutingOperationCompleted = AddressOf Me.OnRoutingOperationCompleted
            End If
            Me.InvokeAsync("Routing", New Object() {bl, ceMercante, RaizCnpj, strusuario, strsenha}, Me.RoutingOperationCompleted, userState)
        End Sub
        
        Private Sub OnRoutingOperationCompleted(ByVal arg As Object)
            If (Not (Me.RoutingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RoutingCompleted(Me, New RoutingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/BloqueadoSN", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function BloqueadoSN(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String) As clsDadosIntegracaoImp
            Dim results() As Object = Me.Invoke("BloqueadoSN", New Object() {bl, ceMercante, RaizCnpj, strusuario, strsenha})
            Return CType(results(0),clsDadosIntegracaoImp)
        End Function
        
        '''<remarks/>
        Public Overloads Sub BloqueadoSNAsync(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String)
            Me.BloqueadoSNAsync(bl, ceMercante, RaizCnpj, strusuario, strsenha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BloqueadoSNAsync(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String, ByVal userState As Object)
            If (Me.BloqueadoSNOperationCompleted Is Nothing) Then
                Me.BloqueadoSNOperationCompleted = AddressOf Me.OnBloqueadoSNOperationCompleted
            End If
            Me.InvokeAsync("BloqueadoSN", New Object() {bl, ceMercante, RaizCnpj, strusuario, strsenha}, Me.BloqueadoSNOperationCompleted, userState)
        End Sub
        
        Private Sub OnBloqueadoSNOperationCompleted(ByVal arg As Object)
            If (Not (Me.BloqueadoSNCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BloqueadoSNCompleted(Me, New BloqueadoSNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eprofesseonal.com/Container", RequestNamespace:="http://eprofesseonal.com/", ResponseNamespace:="http://eprofesseonal.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Container(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String) As clsDadosIntegracaoImp
            Dim results() As Object = Me.Invoke("Container", New Object() {bl, ceMercante, RaizCnpj, strusuario, strsenha})
            Return CType(results(0),clsDadosIntegracaoImp)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ContainerAsync(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String)
            Me.ContainerAsync(bl, ceMercante, RaizCnpj, strusuario, strsenha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ContainerAsync(ByVal bl As String, ByVal ceMercante As String, ByVal RaizCnpj As String, ByVal strusuario As String, ByVal strsenha As String, ByVal userState As Object)
            If (Me.ContainerOperationCompleted Is Nothing) Then
                Me.ContainerOperationCompleted = AddressOf Me.OnContainerOperationCompleted
            End If
            Me.InvokeAsync("Container", New Object() {bl, ceMercante, RaizCnpj, strusuario, strsenha}, Me.ContainerOperationCompleted, userState)
        End Sub
        
        Private Sub OnContainerOperationCompleted(ByVal arg As Object)
            If (Not (Me.ContainerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ContainerCompleted(Me, New ContainerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eprofesseonal.com/")>  _
    Partial Public Class clsDadosIntegracaoImp
        
        Private containerField As String
        
        Private statusBloqueadoField As String
        
        Private routingField As String
        
        Private mensagemRetornoField As clsMensagemRetorno
        
        '''<remarks/>
        Public Property Container() As String
            Get
                Return Me.containerField
            End Get
            Set
                Me.containerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusBloqueado() As String
            Get
                Return Me.statusBloqueadoField
            End Get
            Set
                Me.statusBloqueadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Routing() As String
            Get
                Return Me.routingField
            End Get
            Set
                Me.routingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensagemRetorno() As clsMensagemRetorno
            Get
                Return Me.mensagemRetornoField
            End Get
            Set
                Me.mensagemRetornoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eprofesseonal.com/")>  _
    Partial Public Class clsMensagemRetorno
        
        Private codigoRetornoField As Integer
        
        Private mensagemField As String
        
        '''<remarks/>
        Public Property CodigoRetorno() As Integer
            Get
                Return Me.codigoRetornoField
            End Get
            Set
                Me.codigoRetornoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://eprofesseonal.com/")>  _
    Partial Public Class clsDadosIntegracao
        
        Private ex_ReservaNrField As String
        
        Private ex_ClienteFantaField As String
        
        Private ex_Cliente_CNPJField As String
        
        Private ex_RefClienteField As String
        
        Private ex_SCli_FantaField As String
        
        Private ex_SCli_CNPJField As String
        
        Private ex_DtReservaField As String
        
        Private ex_TpCarga2Field As String
        
        Private ex_QuantidadeField As Integer
        
        Private ex_TipoVolumeField As String
        
        Private ex_PesoField As Double
        
        Private ex_CubagemField As Double
        
        Private ex_NavioField As String
        
        Private ex_DescricaoField As String
        
        Private ex_IdentificadorField As String
        
        Private ex_DestinoField As String
        
        Private ex_ViaField As String
        
        Private ex_IMOField As String
        
        Private ex_ONUField As String
        
        Private ex_DeadLineField As String
        
        Private mensagemRetornoField As clsMensagemRetorno
        
        '''<remarks/>
        Public Property Ex_ReservaNr() As String
            Get
                Return Me.ex_ReservaNrField
            End Get
            Set
                Me.ex_ReservaNrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_ClienteFanta() As String
            Get
                Return Me.ex_ClienteFantaField
            End Get
            Set
                Me.ex_ClienteFantaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Cliente_CNPJ() As String
            Get
                Return Me.ex_Cliente_CNPJField
            End Get
            Set
                Me.ex_Cliente_CNPJField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_RefCliente() As String
            Get
                Return Me.ex_RefClienteField
            End Get
            Set
                Me.ex_RefClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_SCli_Fanta() As String
            Get
                Return Me.ex_SCli_FantaField
            End Get
            Set
                Me.ex_SCli_FantaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_SCli_CNPJ() As String
            Get
                Return Me.ex_SCli_CNPJField
            End Get
            Set
                Me.ex_SCli_CNPJField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_DtReserva() As String
            Get
                Return Me.ex_DtReservaField
            End Get
            Set
                Me.ex_DtReservaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_TpCarga2() As String
            Get
                Return Me.ex_TpCarga2Field
            End Get
            Set
                Me.ex_TpCarga2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Quantidade() As Integer
            Get
                Return Me.ex_QuantidadeField
            End Get
            Set
                Me.ex_QuantidadeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_TipoVolume() As String
            Get
                Return Me.ex_TipoVolumeField
            End Get
            Set
                Me.ex_TipoVolumeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Peso() As Double
            Get
                Return Me.ex_PesoField
            End Get
            Set
                Me.ex_PesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Cubagem() As Double
            Get
                Return Me.ex_CubagemField
            End Get
            Set
                Me.ex_CubagemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Navio() As String
            Get
                Return Me.ex_NavioField
            End Get
            Set
                Me.ex_NavioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Descricao() As String
            Get
                Return Me.ex_DescricaoField
            End Get
            Set
                Me.ex_DescricaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Identificador() As String
            Get
                Return Me.ex_IdentificadorField
            End Get
            Set
                Me.ex_IdentificadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Destino() As String
            Get
                Return Me.ex_DestinoField
            End Get
            Set
                Me.ex_DestinoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_Via() As String
            Get
                Return Me.ex_ViaField
            End Get
            Set
                Me.ex_ViaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_IMO() As String
            Get
                Return Me.ex_IMOField
            End Get
            Set
                Me.ex_IMOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_ONU() As String
            Get
                Return Me.ex_ONUField
            End Get
            Set
                Me.ex_ONUField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ex_DeadLine() As String
            Get
                Return Me.ex_DeadLineField
            End Get
            Set
                Me.ex_DeadLineField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensagemRetorno() As clsMensagemRetorno
            Get
                Return Me.mensagemRetornoField
            End Get
            Set
                Me.mensagemRetornoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub RetornaTabelaCompletedEventHandler(ByVal sender As Object, ByVal e As RetornaTabelaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RetornaTabelaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub ExcluirCompletedEventHandler(ByVal sender As Object, ByVal e As ExcluirCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExcluirCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub ExecutarCompletedEventHandler(ByVal sender As Object, ByVal e As ExecutarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecutarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub ExecutarScalarCompletedEventHandler(ByVal sender As Object, ByVal e As ExecutarScalarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExecutarScalarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub ApontadorCompletedEventHandler(ByVal sender As Object, ByVal e As ApontadorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ApontadorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub RetornaDadosReservaCompletedEventHandler(ByVal sender As Object, ByVal e As RetornaDadosReservaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RetornaDadosReservaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsDadosIntegracao
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsDadosIntegracao)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub RoutingCompletedEventHandler(ByVal sender As Object, ByVal e As RoutingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RoutingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsDadosIntegracaoImp
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsDadosIntegracaoImp)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub BloqueadoSNCompletedEventHandler(ByVal sender As Object, ByVal e As BloqueadoSNCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class BloqueadoSNCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsDadosIntegracaoImp
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsDadosIntegracaoImp)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub ContainerCompletedEventHandler(ByVal sender As Object, ByVal e As ContainerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ContainerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsDadosIntegracaoImp
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsDadosIntegracaoImp)
            End Get
        End Property
    End Class
End Namespace
