CREATE SEQUENCE  OPERADOR.SEQ_AGENDAMENTO_CS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 155 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  OPERADOR.SEQ_AGENDAMENTO_CS_ITENS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 548 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  OPERADOR.SEQ_AGENDAMENTO_CS_PROTOCOLO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 200 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  OPERADOR.SEQ_AG_CS_ITENS_CHASSIS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 529 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  OPERADOR.SEQ_AG_CS_ITENS_DANFES  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 299 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE OPERADOR.TB_AGENDAMENTO_CS 
(	
    AUTONUM NUMBER(*,0) NOT NULL ENABLE, 
    AUTONUM_MOTORISTA NUMBER(*,0) NOT NULL ENABLE, 
    AUTONUM_VEICULO NUMBER(*,0) NOT NULL ENABLE, 
    AUTONUM_TRANSPORTADORA NUMBER(*,0) NOT NULL ENABLE, 
    AUTONUM_PERIODO NUMBER(*,0) NOT NULL ENABLE, 
    DATA_HORA DATE DEFAULT SYSDATE, 
    AUTONUM_USUARIO NUMBER(*,0) NOT NULL ENABLE, 
    PROTOCOLO VARCHAR2(20 BYTE), 
    FLAG_IMPRESSO NUMBER(*,0) DEFAULT 0, 
    AUTONUM_CS_BOOKING NUMBER(*,0) NOT NULL ENABLE, 
    FLAG_CEGONHA NUMBER(1,0) DEFAULT 0, 
    AUTONUM_GATE NUMBER(12,0) DEFAULT 0 NOT NULL ENABLE, 
    ANO_PROTOCOLO NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
    DT_ENTRADA DATE, 
    FLAG_DESEMBARACADO NUMBER(*,0) DEFAULT 0, 
    RESERVA VARCHAR2(30 BYTE), 
    CTE VARCHAR2(35 BYTE), 
    EMAIL_REGISTRO VARCHAR2(400 BYTE), 
 PRIMARY KEY (AUTONUM)
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE DADOS_TECONDI  ENABLE, 
 CONSTRAINT FK_AG_CS_MOTORISTA FOREIGN KEY (AUTONUM_MOTORISTA)
  REFERENCES OPERADOR.TB_AG_MOTORISTAS (AUTONUM) ENABLE, 
 CONSTRAINT FK_AG_CS_VEICULO FOREIGN KEY (AUTONUM_VEICULO)
  REFERENCES OPERADOR.TB_AG_VEICULOS (AUTONUM) ENABLE, 
 CONSTRAINT FK_AG_CS_TRANSPORTADORA FOREIGN KEY (AUTONUM_TRANSPORTADORA)
  REFERENCES OPERADOR.TB_CAD_TRANSPORTADORAS (AUTONUM) ENABLE, 
 CONSTRAINT FK_AG_CS_PERIODO FOREIGN KEY (AUTONUM_PERIODO)
  REFERENCES OPERADOR.TB_GD_RESERVA (AUTONUM_GD_RESERVA) ENABLE
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE DADOS_TECONDI ;


CREATE TABLE OPERADOR.TB_AGENDAMENTO_CS_ITENS 
(	
    AUTONUM NUMBER(*,0) NOT NULL ENABLE, 
    AUTONUM_AGENDAMENTO NUMBER(*,0) NOT NULL ENABLE, 
    AUTONUM_CS_BOOKING_ITEM NUMBER(*,0) NOT NULL ENABLE, 
    QTDE NUMBER(*,0) NOT NULL ENABLE, 
    DANFE VARCHAR2(44 BYTE), 
    NUMERO_NF NUMBER(*,0), 
    SERIE VARCHAR2(10 BYTE), 
    CFOP VARCHAR2(8 BYTE), 
    CHASSIS VARCHAR(4000), 
     PRIMARY KEY (AUTONUM)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE DADOS_TECONDI  ENABLE, 
     FOREIGN KEY (AUTONUM_AGENDAMENTO)
      REFERENCES OPERADOR.TB_AGENDAMENTO_CS (AUTONUM) ENABLE
    ) SEGMENT CREATION IMMEDIATE 
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE DADOS_TECONDI ;


  CREATE TABLE OPERADOR.TB_AGENDAMENTO_CS_ITENS_CHASSI 
   (	AUTONUM NUMBER(*,0) NOT NULL ENABLE, 
	AUTONUM_AGENDAMENTO_ITEM NUMBER(*,0) NOT NULL ENABLE, 
	CHASSI VARCHAR2(50 BYTE), 
	 PRIMARY KEY (AUTONUM)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI  ENABLE, 
	 CONSTRAINT TB_AGENDAMENTO_CS_ITENS_C_FK1 FOREIGN KEY (AUTONUM_AGENDAMENTO_ITEM)
	  REFERENCES OPERADOR.TB_AGENDAMENTO_CS_ITENS (AUTONUM) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI ;
 

  CREATE TABLE OPERADOR.TB_AGENDAMENTO_CS_ITENS_DANFES 
   (	AUTONUM NUMBER(*,0) NOT NULL ENABLE, 
	AUTONUM_AGENDAMENTO_ITEM NUMBER(*,0) NOT NULL ENABLE, 
	DANFE VARCHAR2(44 BYTE), 
	CFOP VARCHAR2(4 BYTE), 
	 PRIMARY KEY (AUTONUM)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI  ENABLE, 
	 CONSTRAINT TB_AGENDAMENTO_CS_ITENS_D_FK1 FOREIGN KEY (AUTONUM_AGENDAMENTO_ITEM)
	  REFERENCES OPERADOR.TB_AGENDAMENTO_CS_ITENS (AUTONUM) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI ;
 

 
  CREATE TABLE SGIPA.TB_AV_IMAGEM 
   (	
   AUTONUM NUMBER NOT NULL ENABLE, 
	LOTE NUMBER NOT NULL ENABLE, 
	TIPO_DOCUMENTO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	NUM_DOCUMENTO VARCHAR2(20 BYTE), 
	DT_INCLUSAO DATE NOT NULL ENABLE, 
	CAMINHO_IMG VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	NOME_IMG VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	FLAG_AGENDAMENTO NUMBER(1,0), 
	CNTR NUMBER, 
	AUTONUM_AGENDAMENTO_DOC NUMBER, 
	AUTONUM_AGENDAMENTO NUMBER(*,0), 
	 CONSTRAINT TB_AV_IMAGEM_PK PRIMARY KEY (AUTONUM)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI ;

   COMMENT ON COLUMN SGIPA.TB_AV_IMAGEM.AUTONUM IS 'ID DA TABELA';
   COMMENT ON COLUMN SGIPA.TB_AV_IMAGEM.LOTE IS 'NUMERO DO LOTE';
   COMMENT ON COLUMN SGIPA.TB_AV_IMAGEM.TIPO_DOCUMENTO IS 'TIPO DO DOCUMENTO';
   COMMENT ON COLUMN SGIPA.TB_AV_IMAGEM.NUM_DOCUMENTO IS 'NUMERO DO DOCUMENTO';
   COMMENT ON COLUMN SGIPA.TB_AV_IMAGEM.DT_INCLUSAO IS 'DATA DE INCLUSAO';
   COMMENT ON COLUMN SGIPA.TB_AV_IMAGEM.CAMINHO_IMG IS 'CAMINHO DA IMAGEM';
   COMMENT ON COLUMN SGIPA.TB_AV_IMAGEM.NOME_IMG IS 'NOME DA IMAGEM';

  CREATE INDEX SGIPA.IDX_AV_IMAGEM_001 ON SGIPA.TB_AV_IMAGEM (LOTE, AUTONUM_AGENDAMENTO_DOC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI ;

  CREATE INDEX SGIPA.IDX_AV_IMAGEM_002 ON SGIPA.TB_AV_IMAGEM (LOTE, AUTONUM_AGENDAMENTO_DOC, DT_INCLUSAO) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI ;

  CREATE INDEX SGIPA.IDX_AV_IMAGE_003 ON SGIPA.TB_AV_IMAGEM (AUTONUM_AGENDAMENTO_DOC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE DADOS_TECONDI ;

ALTER TABLE SGIPA.TB_AV_IMAGEM ADD TIPO_DOC_AGENDAMENTO VARCHAR(10);

SELECT
    AUTONUM_GD_RESERVA As Id,
    PATIO,
    TO_CHAR(PERIODO_INICIAL, 'DD/MM/YYYY HH24:MI:SS') As PeriodoInicial,
    TO_CHAR(PERIODO_FINAL, 'DD/MM/YYYY HH24:MI:SS') As PeriodoFinal
FROM
    OPERADOR.TB_GD_RESERVA
WHERE
    PERIODO_FINAL < PERIODO_INICIAL
AND
    PERIODO_INICIAL > SYSDATE

UPDATE OPERADOR.TB_GD_RESERVA SET PERIODO_FINAL = TO_DATE(TO_CHAR(PERIODO_INICIAL, 'DD/MM/YYYY') || ' 00:00:59', 'DD/MM/YYYY HH24:MI:SS')+(23/24)+(59/24/60)
WHERE
    PERIODO_FINAL < PERIODO_INICIAL
AND
    PERIODO_INICIAL > SYSDATE;
	
 CREATE OR REPLACE FORCE VIEW OPERADOR.VW_WEB_ITENS_RESERVA (AUTONUM_CS_BOOKING, QTDE_RESERVA, EMBALAGEM, PESO_UNIT, MARCA, CONTRAMARCA, AUTONUM_CS_BOOKING_ITEM, MODELO, FLAG_VEICULO, FLAG_UPLOAD_PACKLIST, FLAG_UPLOAD_IMAGEM_CARGA, FLAG_UPLOAD_D_TECNICO, SALDO, CLASSIFICACAO_DESCRICAO, AUTONUM_CLASSIFICACAO, TRANSP_CHEGADA) AS 
  SELECT i.autonum_cs_booking, i.quantidade AS qtde_reserva,
         e.descr AS embalagem, i.peso_bruto_unit AS peso_unit, i.marca,
         i.contramarca, i.autonum AS autonum_cs_booking_item, i.modelo,
         NVL (CLASS.flag_chassis_agendamento, 0) AS flag_veiculo,
         NVL (CLASS.flag_upload_packlist, 0),
         NVL (CLASS.flag_upload_imagem_carga, 0),
         NVL (CLASS.flag_upload_d_tecnico, 0),
           i.quantidade
         - NVL ((SELECT SUM (b.qtde)
                   FROM tb_agendamento_cs_itens b 
                   inner join tb_agendamento_cs a on b.autonum_agendamento=a.autonum
                  WHERE b.autonum_cs_booking_item = i.autonum and a.autonum_gate=0), 0)

         - NVL ((SELECT SUM (p.quantidade)
                   FROM tb_cs_patio p
                  WHERE p.autonum_cs_booking_item = i.autonum), 0)


                  AS saldo,
         NVL (CLASS.descr, ' ') AS classificacao_desricao,
         NVL (CLASS.autonum, 0) AS autonum_classificacao,
         i.TRANSP_CHEGADA
    FROM operador.tb_cs_booking_item i INNER JOIN operador.tb_cs_booking b
         ON i.autonum_cs_booking = b.autonum
         LEFT JOIN operador.tb_cad_class_cargo CLASS
         ON i.autonum_cargo_class = CLASS.autonum
         LEFT JOIN sgipa.dte_tb_embalagens e ON i.autonum_cs_embalagem =
                                                                        e.code
         LEFT JOIN operador.vw_cs_booking_item_vei vw
         ON i.autonum = vw.autonum_cs_booking_item ;
	