CREATE SEQUENCE  OPERADOR.SEQ_AGENDAMENTO_TRA MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 155 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE  OPERADOR.SEQ_AGENDAMENTO_DEPOT MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 155 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE OPERADOR.TB_AGENDAMENTO_TRA
(	
    AUTONUM NUMBER(*,0) NOT NULL PRIMARY KEY, 
    AUTONUM_MOTORISTA NUMBER(*,0) NOT NULL, 
    AUTONUM_VEICULO NUMBER(*,0) NOT NULL, 
    AUTONUM_TRANSPORTADORA NUMBER(*,0) NOT NULL, 
    AUTONUM_PERIODO NUMBER(*,0), 
    DATA_HORA DATE DEFAULT SYSDATE, 
    AUTONUM_USUARIO NUMBER(*,0) NOT NULL, 
    PROTOCOLO VARCHAR2(20 BYTE), 
    ANO_PROTOCOLO NUMBER(4,0) DEFAULT 0 NOT NULL, 
    FLAG_IMPRESSO NUMBER(*,0) DEFAULT 0,     
    AUTONUM_GATE NUMBER(12,0) DEFAULT 0 NOT NULL,     
    DT_ENTRADA DATE, 
    CTE VARCHAR2(35 BYTE), 
	TIPO_OPERACAO NUMBER(1,0),
    AUTONUM_RECINTO NUMBER(*,0) NOT NULL, 
    QUANTIDADE INT,
    IMO NUMBER(1,0),
    EXCESSO NUMBER(1,0)
);

ALTER TABLE OPERADOR.TB_AGENDAMENTO_TRA ADD CONSTRAINT FK_AG_TRA_VEI FOREIGN KEY (AUTONUM_VEICULO) REFERENCES OPERADOR.TB_AG_VEICULOS(AUTONUM);
ALTER TABLE OPERADOR.TB_AGENDAMENTO_TRA ADD CONSTRAINT FK_AG_TRA_TRA FOREIGN KEY (AUTONUM_TRANSPORTADORA) REFERENCES OPERADOR.TB_CAD_TRANSPORTADORAS(AUTONUM);
ALTER TABLE OPERADOR.TB_AGENDAMENTO_TRA ADD CONSTRAINT FK_AG_TRA_PER FOREIGN KEY (AUTONUM_PERIODO) REFERENCES OPERADOR.TB_GD_RESERVA(AUTONUM_GD_RESERVA);
 
CREATE TABLE OPERADOR.TB_AGENDAMENTO_DEPOT
(	
    AUTONUM NUMBER(*,0) NOT NULL PRIMARY KEY, 
    AUTONUM_MOTORISTA NUMBER(*,0) NOT NULL, 
    AUTONUM_VEICULO NUMBER(*,0) NOT NULL, 
    AUTONUM_TRANSPORTADORA NUMBER(*,0) NOT NULL, 
    AUTONUM_PERIODO NUMBER(*,0), 
    DATA_HORA DATE DEFAULT SYSDATE, 
    AUTONUM_USUARIO NUMBER(*,0) NOT NULL, 
    PROTOCOLO VARCHAR2(20 BYTE), 
    ANO_PROTOCOLO NUMBER(4,0) DEFAULT 0 NOT NULL, 
    FLAG_IMPRESSO NUMBER(*,0) DEFAULT 0,     
    AUTONUM_GATE NUMBER(12,0) DEFAULT 0 NOT NULL,     
    DT_ENTRADA DATE, 
    CTE VARCHAR2(35 BYTE), 
	TIPO_OPERACAO NUMBER(1,0),
    RECINTO VARCHAR(40) NOT NULL, 
    QUANTIDADE INT
);

ALTER TABLE OPERADOR.TB_AGENDAMENTO_DEPOT ADD CONSTRAINT FK_AG_DEPOT_VEI FOREIGN KEY (AUTONUM_VEICULO) REFERENCES OPERADOR.TB_AG_VEICULOS(AUTONUM);
ALTER TABLE OPERADOR.TB_AGENDAMENTO_DEPOT ADD CONSTRAINT FK_AG_DEPOT_TRA FOREIGN KEY (AUTONUM_TRANSPORTADORA) REFERENCES OPERADOR.TB_CAD_TRANSPORTADORAS(AUTONUM);
ALTER TABLE OPERADOR.TB_AGENDAMENTO_DEPOT ADD CONSTRAINT FK_AG_DEPOT_PER FOREIGN KEY (AUTONUM_PERIODO) REFERENCES OPERADOR.TB_GD_RESERVA(AUTONUM_GD_RESERVA);