'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WebServiceTecondi
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TecondiBdccResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TecondiBdccResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoRetornoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescricaoRetornoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CodigoRetorno() As String
            Get
                Return Me.CodigoRetornoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoRetornoField, value) <> true) Then
                    Me.CodigoRetornoField = value
                    Me.RaisePropertyChanged("CodigoRetorno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DescricaoRetorno() As String
            Get
                Return Me.DescricaoRetornoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescricaoRetornoField, value) <> true) Then
                    Me.DescricaoRetornoField = value
                    Me.RaisePropertyChanged("DescricaoRetorno")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TecondiBdccCrachaResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TecondiBdccCrachaResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoRetornoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescricaoRetornoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoCrachaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SituacaoCrachaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CodigoRetorno() As String
            Get
                Return Me.CodigoRetornoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoRetornoField, value) <> true) Then
                    Me.CodigoRetornoField = value
                    Me.RaisePropertyChanged("CodigoRetorno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property DescricaoRetorno() As String
            Get
                Return Me.DescricaoRetornoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescricaoRetornoField, value) <> true) Then
                    Me.DescricaoRetornoField = value
                    Me.RaisePropertyChanged("DescricaoRetorno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property CodigoCracha() As String
            Get
                Return Me.CodigoCrachaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoCrachaField, value) <> true) Then
                    Me.CodigoCrachaField = value
                    Me.RaisePropertyChanged("CodigoCracha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property SituacaoCracha() As String
            Get
                Return Me.SituacaoCrachaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SituacaoCrachaField, value) <> true) Then
                    Me.SituacaoCrachaField = value
                    Me.RaisePropertyChanged("SituacaoCracha")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BdccAcesso", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BdccAcesso
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroCrachaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroDocumentoField As String
        
        Private DataAcessoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocalizacaoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioLogadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IpField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property NumeroCracha() As String
            Get
                Return Me.NumeroCrachaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroCrachaField, value) <> true) Then
                    Me.NumeroCrachaField = value
                    Me.RaisePropertyChanged("NumeroCracha")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.TipoDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoDocumentoField, value) <> true) Then
                    Me.TipoDocumentoField = value
                    Me.RaisePropertyChanged("TipoDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property NumeroDocumento() As String
            Get
                Return Me.NumeroDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroDocumentoField, value) <> true) Then
                    Me.NumeroDocumentoField = value
                    Me.RaisePropertyChanged("NumeroDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property DataAcesso() As Date
            Get
                Return Me.DataAcessoField
            End Get
            Set
                If (Me.DataAcessoField.Equals(value) <> true) Then
                    Me.DataAcessoField = value
                    Me.RaisePropertyChanged("DataAcesso")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Localizacao() As String
            Get
                Return Me.LocalizacaoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocalizacaoField, value) <> true) Then
                    Me.LocalizacaoField = value
                    Me.RaisePropertyChanged("Localizacao")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property UsuarioLogado() As String
            Get
                Return Me.UsuarioLogadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioLogadoField, value) <> true) Then
                    Me.UsuarioLogadoField = value
                    Me.RaisePropertyChanged("UsuarioLogado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Ip() As String
            Get
                Return Me.IpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IpField, value) <> true) Then
                    Me.IpField = value
                    Me.RaisePropertyChanged("Ip")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", ConfigurationName:="WebServiceTecondi.WsSincronoSoap")>  _
    Public Interface WsSincronoSoap
        
        'CODEGEN: Generating message contract since element name cpf from namespace http://tecondi.com.br/services/TecondiBdccWs is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tecondi.com.br/services/TecondiBdccWs/ConsultaCpf", ReplyAction:="*")>  _
        Function ConsultaCpf(ByVal request As WebServiceTecondi.ConsultaCpfRequest) As WebServiceTecondi.ConsultaCpfResponse
        
        'CODEGEN: Generating message contract since element name renavam from namespace http://tecondi.com.br/services/TecondiBdccWs is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tecondi.com.br/services/TecondiBdccWs/ConsultaRenavam", ReplyAction:="*")>  _
        Function ConsultaRenavam(ByVal request As WebServiceTecondi.ConsultaRenavamRequest) As WebServiceTecondi.ConsultaRenavamResponse
        
        'CODEGEN: Generating message contract since element name cracha from namespace http://tecondi.com.br/services/TecondiBdccWs is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tecondi.com.br/services/TecondiBdccWs/ConsultaCracha", ReplyAction:="*")>  _
        Function ConsultaCracha(ByVal request As WebServiceTecondi.ConsultaCrachaRequest) As WebServiceTecondi.ConsultaCrachaResponse
        
        'CODEGEN: Generating message contract since element name numeroCracha from namespace http://tecondi.com.br/services/TecondiBdccWs is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tecondi.com.br/services/TecondiBdccWs/RegistraEntrada", ReplyAction:="*")>  _
        Function RegistraEntrada(ByVal request As WebServiceTecondi.RegistraEntradaRequest) As WebServiceTecondi.RegistraEntradaResponse
        
        'CODEGEN: Generating message contract since element name VerificacaoSGBDCCResult from namespace http://tecondi.com.br/services/TecondiBdccWs is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tecondi.com.br/services/TecondiBdccWs/VerificacaoSGBDCC", ReplyAction:="*")>  _
        Function VerificacaoSGBDCC(ByVal request As WebServiceTecondi.VerificacaoSGBDCCRequest) As WebServiceTecondi.VerificacaoSGBDCCResponse
        
        'CODEGEN: Generating message contract since element name dataInicial from namespace http://tecondi.com.br/services/TecondiBdccWs is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tecondi.com.br/services/TecondiBdccWs/ListaAcessos", ReplyAction:="*")>  _
        Function ListaAcessos(ByVal request As WebServiceTecondi.ListaAcessosRequest) As WebServiceTecondi.ListaAcessosResponse
        
        'CODEGEN: Generating message contract since element name cpf from namespace http://tecondi.com.br/services/TecondiBdccWs is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tecondi.com.br/services/TecondiBdccWs/ConsultaCpfIntranet", ReplyAction:="*")>  _
        Function ConsultaCpfIntranet(ByVal request As WebServiceTecondi.ConsultaCpfIntranetRequest) As WebServiceTecondi.ConsultaCpfIntranetResponse
        
        'CODEGEN: Generating message contract since element name cnpj from namespace http://tecondi.com.br/services/TecondiBdccWs is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tecondi.com.br/services/TecondiBdccWs/ConsultaCNPJIntranet", ReplyAction:="*")>  _
        Function ConsultaCNPJIntranet(ByVal request As WebServiceTecondi.ConsultaCNPJIntranetRequest) As WebServiceTecondi.ConsultaCNPJIntranetResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaCpfRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaCpf", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaCpfRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaCpfRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaCpfRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cpf As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public registraEntradaSemCracha As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public cnpj As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public autonomo As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer, ByVal cnpj As String, ByVal autonomo As Integer)
            MyBase.New
            Me.cpf = cpf
            Me.registraEntradaSemCracha = registraEntradaSemCracha
            Me.cnpj = cnpj
            Me.autonomo = autonomo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaCpfResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaCpfResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaCpfResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaCpfResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaCpfResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultaCpfResult As WebServiceTecondi.TecondiBdccResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultaCpfResult As WebServiceTecondi.TecondiBdccResponse)
            MyBase.New
            Me.ConsultaCpfResult = ConsultaCpfResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaRenavamRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaRenavam", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaRenavamRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaRenavamRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaRenavamRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public renavam As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public registraEntradaSemCracha As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal renavam As String, ByVal registraEntradaSemCracha As Integer)
            MyBase.New
            Me.renavam = renavam
            Me.registraEntradaSemCracha = registraEntradaSemCracha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaRenavamResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaRenavamResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaRenavamResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaRenavamResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaRenavamResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultaRenavamResult As WebServiceTecondi.TecondiBdccResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultaRenavamResult As WebServiceTecondi.TecondiBdccResponse)
            MyBase.New
            Me.ConsultaRenavamResult = ConsultaRenavamResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaCrachaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaCracha", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaCrachaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaCrachaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaCrachaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cracha As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cracha As String)
            MyBase.New
            Me.cracha = cracha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaCrachaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaCrachaResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaCrachaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaCrachaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaCrachaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultaCrachaResult As WebServiceTecondi.TecondiBdccCrachaResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultaCrachaResult As WebServiceTecondi.TecondiBdccCrachaResponse)
            MyBase.New
            Me.ConsultaCrachaResult = ConsultaCrachaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RegistraEntradaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RegistraEntrada", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.RegistraEntradaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.RegistraEntradaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class RegistraEntradaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public numeroCracha As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public tipoDocumento As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public numeroDocumento As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public local As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public usuarioLogado As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public ip As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal numeroCracha As String, ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal local As String, ByVal usuarioLogado As String, ByVal ip As String)
            MyBase.New
            Me.numeroCracha = numeroCracha
            Me.tipoDocumento = tipoDocumento
            Me.numeroDocumento = numeroDocumento
            Me.local = local
            Me.usuarioLogado = usuarioLogado
            Me.ip = ip
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RegistraEntradaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RegistraEntradaResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.RegistraEntradaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.RegistraEntradaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class RegistraEntradaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VerificacaoSGBDCCRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VerificacaoSGBDCC", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.VerificacaoSGBDCCRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.VerificacaoSGBDCCRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class VerificacaoSGBDCCRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VerificacaoSGBDCCResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VerificacaoSGBDCCResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.VerificacaoSGBDCCResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.VerificacaoSGBDCCResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class VerificacaoSGBDCCResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public VerificacaoSGBDCCResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VerificacaoSGBDCCResult As String)
            MyBase.New
            Me.VerificacaoSGBDCCResult = VerificacaoSGBDCCResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListaAcessosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListaAcessos", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ListaAcessosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ListaAcessosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ListaAcessosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public dataInicial As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public dataFinal As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public local As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal dataInicial As String, ByVal dataFinal As String, ByVal local As String)
            MyBase.New
            Me.dataInicial = dataInicial
            Me.dataFinal = dataFinal
            Me.local = local
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListaAcessosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListaAcessosResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ListaAcessosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ListaAcessosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ListaAcessosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListaAcessosResult() As WebServiceTecondi.BdccAcesso
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListaAcessosResult() As WebServiceTecondi.BdccAcesso)
            MyBase.New
            Me.ListaAcessosResult = ListaAcessosResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaCpfIntranetRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaCpfIntranet", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaCpfIntranetRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaCpfIntranetRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaCpfIntranetRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cpf As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public registraEntradaSemCracha As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer)
            MyBase.New
            Me.cpf = cpf
            Me.registraEntradaSemCracha = registraEntradaSemCracha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaCpfIntranetResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaCpfIntranetResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaCpfIntranetResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaCpfIntranetResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaCpfIntranetResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultaCpfIntranetResult As WebServiceTecondi.TecondiBdccResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultaCpfIntranetResult As WebServiceTecondi.TecondiBdccResponse)
            MyBase.New
            Me.ConsultaCpfIntranetResult = ConsultaCpfIntranetResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaCNPJIntranetRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaCNPJIntranet", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaCNPJIntranetRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaCNPJIntranetRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaCNPJIntranetRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cnpj As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public autonomo As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cnpj As String, ByVal autonomo As Integer)
            MyBase.New
            Me.cnpj = cnpj
            Me.autonomo = autonomo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaCNPJIntranetResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaCNPJIntranetResponse", [Namespace]:="http://tecondi.com.br/services/TecondiBdccWs", Order:=0)>  _
        Public Body As WebServiceTecondi.ConsultaCNPJIntranetResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebServiceTecondi.ConsultaCNPJIntranetResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tecondi.com.br/services/TecondiBdccWs")>  _
    Partial Public Class ConsultaCNPJIntranetResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultaCNPJIntranetResult As WebServiceTecondi.TecondiBdccResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultaCNPJIntranetResult As WebServiceTecondi.TecondiBdccResponse)
            MyBase.New
            Me.ConsultaCNPJIntranetResult = ConsultaCNPJIntranetResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WsSincronoSoapChannel
        Inherits WebServiceTecondi.WsSincronoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WsSincronoSoapClient
        Inherits System.ServiceModel.ClientBase(Of WebServiceTecondi.WsSincronoSoap)
        Implements WebServiceTecondi.WsSincronoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceTecondi_WsSincronoSoap_ConsultaCpf(ByVal request As WebServiceTecondi.ConsultaCpfRequest) As WebServiceTecondi.ConsultaCpfResponse Implements WebServiceTecondi.WsSincronoSoap.ConsultaCpf
            Return MyBase.Channel.ConsultaCpf(request)
        End Function
        
        Public Function ConsultaCpf(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer, ByVal cnpj As String, ByVal autonomo As Integer) As WebServiceTecondi.TecondiBdccResponse
            Dim inValue As WebServiceTecondi.ConsultaCpfRequest = New WebServiceTecondi.ConsultaCpfRequest()
            inValue.Body = New WebServiceTecondi.ConsultaCpfRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.registraEntradaSemCracha = registraEntradaSemCracha
            inValue.Body.cnpj = cnpj
            inValue.Body.autonomo = autonomo
            Dim retVal As WebServiceTecondi.ConsultaCpfResponse = CType(Me,WebServiceTecondi.WsSincronoSoap).ConsultaCpf(inValue)
            Return retVal.Body.ConsultaCpfResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceTecondi_WsSincronoSoap_ConsultaRenavam(ByVal request As WebServiceTecondi.ConsultaRenavamRequest) As WebServiceTecondi.ConsultaRenavamResponse Implements WebServiceTecondi.WsSincronoSoap.ConsultaRenavam
            Return MyBase.Channel.ConsultaRenavam(request)
        End Function
        
        Public Function ConsultaRenavam(ByVal renavam As String, ByVal registraEntradaSemCracha As Integer) As WebServiceTecondi.TecondiBdccResponse
            Dim inValue As WebServiceTecondi.ConsultaRenavamRequest = New WebServiceTecondi.ConsultaRenavamRequest()
            inValue.Body = New WebServiceTecondi.ConsultaRenavamRequestBody()
            inValue.Body.renavam = renavam
            inValue.Body.registraEntradaSemCracha = registraEntradaSemCracha
            Dim retVal As WebServiceTecondi.ConsultaRenavamResponse = CType(Me,WebServiceTecondi.WsSincronoSoap).ConsultaRenavam(inValue)
            Return retVal.Body.ConsultaRenavamResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceTecondi_WsSincronoSoap_ConsultaCracha(ByVal request As WebServiceTecondi.ConsultaCrachaRequest) As WebServiceTecondi.ConsultaCrachaResponse Implements WebServiceTecondi.WsSincronoSoap.ConsultaCracha
            Return MyBase.Channel.ConsultaCracha(request)
        End Function
        
        Public Function ConsultaCracha(ByVal cracha As String) As WebServiceTecondi.TecondiBdccCrachaResponse
            Dim inValue As WebServiceTecondi.ConsultaCrachaRequest = New WebServiceTecondi.ConsultaCrachaRequest()
            inValue.Body = New WebServiceTecondi.ConsultaCrachaRequestBody()
            inValue.Body.cracha = cracha
            Dim retVal As WebServiceTecondi.ConsultaCrachaResponse = CType(Me,WebServiceTecondi.WsSincronoSoap).ConsultaCracha(inValue)
            Return retVal.Body.ConsultaCrachaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceTecondi_WsSincronoSoap_RegistraEntrada(ByVal request As WebServiceTecondi.RegistraEntradaRequest) As WebServiceTecondi.RegistraEntradaResponse Implements WebServiceTecondi.WsSincronoSoap.RegistraEntrada
            Return MyBase.Channel.RegistraEntrada(request)
        End Function
        
        Public Sub RegistraEntrada(ByVal numeroCracha As String, ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal local As String, ByVal usuarioLogado As String, ByVal ip As String)
            Dim inValue As WebServiceTecondi.RegistraEntradaRequest = New WebServiceTecondi.RegistraEntradaRequest()
            inValue.Body = New WebServiceTecondi.RegistraEntradaRequestBody()
            inValue.Body.numeroCracha = numeroCracha
            inValue.Body.tipoDocumento = tipoDocumento
            inValue.Body.numeroDocumento = numeroDocumento
            inValue.Body.local = local
            inValue.Body.usuarioLogado = usuarioLogado
            inValue.Body.ip = ip
            Dim retVal As WebServiceTecondi.RegistraEntradaResponse = CType(Me,WebServiceTecondi.WsSincronoSoap).RegistraEntrada(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceTecondi_WsSincronoSoap_VerificacaoSGBDCC(ByVal request As WebServiceTecondi.VerificacaoSGBDCCRequest) As WebServiceTecondi.VerificacaoSGBDCCResponse Implements WebServiceTecondi.WsSincronoSoap.VerificacaoSGBDCC
            Return MyBase.Channel.VerificacaoSGBDCC(request)
        End Function
        
        Public Function VerificacaoSGBDCC() As String
            Dim inValue As WebServiceTecondi.VerificacaoSGBDCCRequest = New WebServiceTecondi.VerificacaoSGBDCCRequest()
            inValue.Body = New WebServiceTecondi.VerificacaoSGBDCCRequestBody()
            Dim retVal As WebServiceTecondi.VerificacaoSGBDCCResponse = CType(Me,WebServiceTecondi.WsSincronoSoap).VerificacaoSGBDCC(inValue)
            Return retVal.Body.VerificacaoSGBDCCResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceTecondi_WsSincronoSoap_ListaAcessos(ByVal request As WebServiceTecondi.ListaAcessosRequest) As WebServiceTecondi.ListaAcessosResponse Implements WebServiceTecondi.WsSincronoSoap.ListaAcessos
            Return MyBase.Channel.ListaAcessos(request)
        End Function
        
        Public Function ListaAcessos(ByVal dataInicial As String, ByVal dataFinal As String, ByVal local As String) As WebServiceTecondi.BdccAcesso()
            Dim inValue As WebServiceTecondi.ListaAcessosRequest = New WebServiceTecondi.ListaAcessosRequest()
            inValue.Body = New WebServiceTecondi.ListaAcessosRequestBody()
            inValue.Body.dataInicial = dataInicial
            inValue.Body.dataFinal = dataFinal
            inValue.Body.local = local
            Dim retVal As WebServiceTecondi.ListaAcessosResponse = CType(Me,WebServiceTecondi.WsSincronoSoap).ListaAcessos(inValue)
            Return retVal.Body.ListaAcessosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceTecondi_WsSincronoSoap_ConsultaCpfIntranet(ByVal request As WebServiceTecondi.ConsultaCpfIntranetRequest) As WebServiceTecondi.ConsultaCpfIntranetResponse Implements WebServiceTecondi.WsSincronoSoap.ConsultaCpfIntranet
            Return MyBase.Channel.ConsultaCpfIntranet(request)
        End Function
        
        Public Function ConsultaCpfIntranet(ByVal cpf As String, ByVal registraEntradaSemCracha As Integer) As WebServiceTecondi.TecondiBdccResponse
            Dim inValue As WebServiceTecondi.ConsultaCpfIntranetRequest = New WebServiceTecondi.ConsultaCpfIntranetRequest()
            inValue.Body = New WebServiceTecondi.ConsultaCpfIntranetRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.registraEntradaSemCracha = registraEntradaSemCracha
            Dim retVal As WebServiceTecondi.ConsultaCpfIntranetResponse = CType(Me,WebServiceTecondi.WsSincronoSoap).ConsultaCpfIntranet(inValue)
            Return retVal.Body.ConsultaCpfIntranetResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebServiceTecondi_WsSincronoSoap_ConsultaCNPJIntranet(ByVal request As WebServiceTecondi.ConsultaCNPJIntranetRequest) As WebServiceTecondi.ConsultaCNPJIntranetResponse Implements WebServiceTecondi.WsSincronoSoap.ConsultaCNPJIntranet
            Return MyBase.Channel.ConsultaCNPJIntranet(request)
        End Function
        
        Public Function ConsultaCNPJIntranet(ByVal cnpj As String, ByVal autonomo As Integer) As WebServiceTecondi.TecondiBdccResponse
            Dim inValue As WebServiceTecondi.ConsultaCNPJIntranetRequest = New WebServiceTecondi.ConsultaCNPJIntranetRequest()
            inValue.Body = New WebServiceTecondi.ConsultaCNPJIntranetRequestBody()
            inValue.Body.cnpj = cnpj
            inValue.Body.autonomo = autonomo
            Dim retVal As WebServiceTecondi.ConsultaCNPJIntranetResponse = CType(Me,WebServiceTecondi.WsSincronoSoap).ConsultaCNPJIntranet(inValue)
            Return retVal.Body.ConsultaCNPJIntranetResult
        End Function
    End Class
End Namespace
