'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WsControleSenha
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WsControleSenha.CriptografiaSoap")>  _
    Public Interface CriptografiaSoap
        
        'CODEGEN: Generating message contract since element name nomeSistema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EncriptarTabela", ReplyAction:="*")>  _
        Function EncriptarTabela(ByVal request As WsControleSenha.EncriptarTabelaRequest) As WsControleSenha.EncriptarTabelaResponse
        
        'CODEGEN: Generating message contract since element name nomeSistema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DescriptarTabela", ReplyAction:="*")>  _
        Function DescriptarTabela(ByVal request As WsControleSenha.DescriptarTabelaRequest) As WsControleSenha.DescriptarTabelaResponse
        
        'CODEGEN: Generating message contract since element name nomeSistema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObterVersao", ReplyAction:="*")>  _
        Function ObterVersao(ByVal request As WsControleSenha.ObterVersaoRequest) As WsControleSenha.ObterVersaoResponse
        
        'CODEGEN: Generating message contract since element name nomeSistema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObterTabelaLogin", ReplyAction:="*")>  _
        Function ObterTabelaLogin(ByVal request As WsControleSenha.ObterTabelaLoginRequest) As WsControleSenha.ObterTabelaLoginResponse
        
        'CODEGEN: Generating message contract since element name tabela from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/usuLogOut", ReplyAction:="*")>  _
        Function usuLogOut(ByVal request As WsControleSenha.usuLogOutRequest) As WsControleSenha.usuLogOutResponse
        
        'CODEGEN: Generating message contract since element name tabela from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ValidarUsuario", ReplyAction:="*")>  _
        Function ValidarUsuario(ByVal request As WsControleSenha.ValidarUsuarioRequest) As WsControleSenha.ValidarUsuarioResponse
        
        'CODEGEN: Generating message contract since element name tabela from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ValidarUsuarioCPF", ReplyAction:="*")>  _
        Function ValidarUsuarioCPF(ByVal request As WsControleSenha.ValidarUsuarioCPFRequest) As WsControleSenha.ValidarUsuarioCPFResponse
        
        'CODEGEN: Generating message contract since element name novaSenha from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/alterarSenha", ReplyAction:="*")>  _
        Function alterarSenha(ByVal request As WsControleSenha.alterarSenhaRequest) As WsControleSenha.alterarSenhaResponse
        
        'CODEGEN: Generating message contract since element name schema from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RetornaSenhaBD", ReplyAction:="*")>  _
        Function RetornaSenhaBD(ByVal request As WsControleSenha.RetornaSenhaBDRequest) As WsControleSenha.RetornaSenhaBDResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EncriptarTabelaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EncriptarTabela", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.EncriptarTabelaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.EncriptarTabelaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EncriptarTabelaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nomeSistema As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeSistema As String)
            MyBase.New
            Me.nomeSistema = nomeSistema
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EncriptarTabelaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EncriptarTabelaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.EncriptarTabelaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.EncriptarTabelaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EncriptarTabelaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EncriptarTabelaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncriptarTabelaResult As String)
            MyBase.New
            Me.EncriptarTabelaResult = EncriptarTabelaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DescriptarTabelaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DescriptarTabela", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.DescriptarTabelaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.DescriptarTabelaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DescriptarTabelaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nomeSistema As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeSistema As String)
            MyBase.New
            Me.nomeSistema = nomeSistema
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DescriptarTabelaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DescriptarTabelaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.DescriptarTabelaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.DescriptarTabelaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DescriptarTabelaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DescriptarTabelaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DescriptarTabelaResult As String)
            MyBase.New
            Me.DescriptarTabelaResult = DescriptarTabelaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObterVersaoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObterVersao", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.ObterVersaoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.ObterVersaoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObterVersaoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nomeSistema As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeSistema As String)
            MyBase.New
            Me.nomeSistema = nomeSistema
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObterVersaoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObterVersaoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.ObterVersaoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.ObterVersaoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObterVersaoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObterVersaoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObterVersaoResult As String)
            MyBase.New
            Me.ObterVersaoResult = ObterVersaoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObterTabelaLoginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObterTabelaLogin", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.ObterTabelaLoginRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.ObterTabelaLoginRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObterTabelaLoginRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nomeSistema As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nomeSistema As String)
            MyBase.New
            Me.nomeSistema = nomeSistema
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObterTabelaLoginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObterTabelaLoginResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.ObterTabelaLoginResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.ObterTabelaLoginResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObterTabelaLoginResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObterTabelaLoginResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObterTabelaLoginResult As String)
            MyBase.New
            Me.ObterTabelaLoginResult = ObterTabelaLoginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class usuLogOutRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="usuLogOut", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.usuLogOutRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.usuLogOutRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class usuLogOutRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public tabela As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public usuario As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tabela As String, ByVal usuario As String)
            MyBase.New
            Me.tabela = tabela
            Me.usuario = usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class usuLogOutResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="usuLogOutResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.usuLogOutResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.usuLogOutResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class usuLogOutResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuLogOutResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuLogOutResult As String)
            MyBase.New
            Me.usuLogOutResult = usuLogOutResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ValidarUsuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ValidarUsuario", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.ValidarUsuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.ValidarUsuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public tabela As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public senha As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tabela As String, ByVal usuario As String, ByVal senha As String)
            MyBase.New
            Me.tabela = tabela
            Me.usuario = usuario
            Me.senha = senha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ValidarUsuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ValidarUsuarioResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.ValidarUsuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.ValidarUsuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ValidarUsuarioResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ValidarUsuarioResult As String)
            MyBase.New
            Me.ValidarUsuarioResult = ValidarUsuarioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ValidarUsuarioCPFRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ValidarUsuarioCPF", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.ValidarUsuarioCPFRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.ValidarUsuarioCPFRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioCPFRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public tabela As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public cpf As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tabela As String, ByVal usuario As String, ByVal cpf As String)
            MyBase.New
            Me.tabela = tabela
            Me.usuario = usuario
            Me.cpf = cpf
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ValidarUsuarioCPFResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ValidarUsuarioCPFResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.ValidarUsuarioCPFResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.ValidarUsuarioCPFResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ValidarUsuarioCPFResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ValidarUsuarioCPFResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ValidarUsuarioCPFResult As String)
            MyBase.New
            Me.ValidarUsuarioCPFResult = ValidarUsuarioCPFResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class alterarSenhaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="alterarSenha", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.alterarSenhaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.alterarSenhaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class alterarSenhaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public novaSenha As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public tabela As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public login As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal novaSenha As String, ByVal tabela As String, ByVal login As String)
            MyBase.New
            Me.novaSenha = novaSenha
            Me.tabela = tabela
            Me.login = login
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class alterarSenhaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="alterarSenhaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.alterarSenhaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.alterarSenhaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class alterarSenhaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public alterarSenhaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal alterarSenhaResult As String)
            MyBase.New
            Me.alterarSenhaResult = alterarSenhaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RetornaSenhaBDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RetornaSenhaBD", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.RetornaSenhaBDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.RetornaSenhaBDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RetornaSenhaBDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public schema As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public baseHomologacao As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal schema As String, ByVal baseHomologacao As Boolean)
            MyBase.New
            Me.schema = schema
            Me.baseHomologacao = baseHomologacao
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RetornaSenhaBDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RetornaSenhaBDResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WsControleSenha.RetornaSenhaBDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WsControleSenha.RetornaSenhaBDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RetornaSenhaBDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RetornaSenhaBDResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetornaSenhaBDResult As String)
            MyBase.New
            Me.RetornaSenhaBDResult = RetornaSenhaBDResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CriptografiaSoapChannel
        Inherits WsControleSenha.CriptografiaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CriptografiaSoapClient
        Inherits System.ServiceModel.ClientBase(Of WsControleSenha.CriptografiaSoap)
        Implements WsControleSenha.CriptografiaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_EncriptarTabela(ByVal request As WsControleSenha.EncriptarTabelaRequest) As WsControleSenha.EncriptarTabelaResponse Implements WsControleSenha.CriptografiaSoap.EncriptarTabela
            Return MyBase.Channel.EncriptarTabela(request)
        End Function
        
        Public Function EncriptarTabela(ByVal nomeSistema As String) As String
            Dim inValue As WsControleSenha.EncriptarTabelaRequest = New WsControleSenha.EncriptarTabelaRequest()
            inValue.Body = New WsControleSenha.EncriptarTabelaRequestBody()
            inValue.Body.nomeSistema = nomeSistema
            Dim retVal As WsControleSenha.EncriptarTabelaResponse = CType(Me,WsControleSenha.CriptografiaSoap).EncriptarTabela(inValue)
            Return retVal.Body.EncriptarTabelaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_DescriptarTabela(ByVal request As WsControleSenha.DescriptarTabelaRequest) As WsControleSenha.DescriptarTabelaResponse Implements WsControleSenha.CriptografiaSoap.DescriptarTabela
            Return MyBase.Channel.DescriptarTabela(request)
        End Function
        
        Public Function DescriptarTabela(ByVal nomeSistema As String) As String
            Dim inValue As WsControleSenha.DescriptarTabelaRequest = New WsControleSenha.DescriptarTabelaRequest()
            inValue.Body = New WsControleSenha.DescriptarTabelaRequestBody()
            inValue.Body.nomeSistema = nomeSistema
            Dim retVal As WsControleSenha.DescriptarTabelaResponse = CType(Me,WsControleSenha.CriptografiaSoap).DescriptarTabela(inValue)
            Return retVal.Body.DescriptarTabelaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_ObterVersao(ByVal request As WsControleSenha.ObterVersaoRequest) As WsControleSenha.ObterVersaoResponse Implements WsControleSenha.CriptografiaSoap.ObterVersao
            Return MyBase.Channel.ObterVersao(request)
        End Function
        
        Public Function ObterVersao(ByVal nomeSistema As String) As String
            Dim inValue As WsControleSenha.ObterVersaoRequest = New WsControleSenha.ObterVersaoRequest()
            inValue.Body = New WsControleSenha.ObterVersaoRequestBody()
            inValue.Body.nomeSistema = nomeSistema
            Dim retVal As WsControleSenha.ObterVersaoResponse = CType(Me,WsControleSenha.CriptografiaSoap).ObterVersao(inValue)
            Return retVal.Body.ObterVersaoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_ObterTabelaLogin(ByVal request As WsControleSenha.ObterTabelaLoginRequest) As WsControleSenha.ObterTabelaLoginResponse Implements WsControleSenha.CriptografiaSoap.ObterTabelaLogin
            Return MyBase.Channel.ObterTabelaLogin(request)
        End Function
        
        Public Function ObterTabelaLogin(ByVal nomeSistema As String) As String
            Dim inValue As WsControleSenha.ObterTabelaLoginRequest = New WsControleSenha.ObterTabelaLoginRequest()
            inValue.Body = New WsControleSenha.ObterTabelaLoginRequestBody()
            inValue.Body.nomeSistema = nomeSistema
            Dim retVal As WsControleSenha.ObterTabelaLoginResponse = CType(Me,WsControleSenha.CriptografiaSoap).ObterTabelaLogin(inValue)
            Return retVal.Body.ObterTabelaLoginResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_usuLogOut(ByVal request As WsControleSenha.usuLogOutRequest) As WsControleSenha.usuLogOutResponse Implements WsControleSenha.CriptografiaSoap.usuLogOut
            Return MyBase.Channel.usuLogOut(request)
        End Function
        
        Public Function usuLogOut(ByVal tabela As String, ByVal usuario As String) As String
            Dim inValue As WsControleSenha.usuLogOutRequest = New WsControleSenha.usuLogOutRequest()
            inValue.Body = New WsControleSenha.usuLogOutRequestBody()
            inValue.Body.tabela = tabela
            inValue.Body.usuario = usuario
            Dim retVal As WsControleSenha.usuLogOutResponse = CType(Me,WsControleSenha.CriptografiaSoap).usuLogOut(inValue)
            Return retVal.Body.usuLogOutResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_ValidarUsuario(ByVal request As WsControleSenha.ValidarUsuarioRequest) As WsControleSenha.ValidarUsuarioResponse Implements WsControleSenha.CriptografiaSoap.ValidarUsuario
            Return MyBase.Channel.ValidarUsuario(request)
        End Function
        
        Public Function ValidarUsuario(ByVal tabela As String, ByVal usuario As String, ByVal senha As String) As String
            Dim inValue As WsControleSenha.ValidarUsuarioRequest = New WsControleSenha.ValidarUsuarioRequest()
            inValue.Body = New WsControleSenha.ValidarUsuarioRequestBody()
            inValue.Body.tabela = tabela
            inValue.Body.usuario = usuario
            inValue.Body.senha = senha
            Dim retVal As WsControleSenha.ValidarUsuarioResponse = CType(Me,WsControleSenha.CriptografiaSoap).ValidarUsuario(inValue)
            Return retVal.Body.ValidarUsuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_ValidarUsuarioCPF(ByVal request As WsControleSenha.ValidarUsuarioCPFRequest) As WsControleSenha.ValidarUsuarioCPFResponse Implements WsControleSenha.CriptografiaSoap.ValidarUsuarioCPF
            Return MyBase.Channel.ValidarUsuarioCPF(request)
        End Function
        
        Public Function ValidarUsuarioCPF(ByVal tabela As String, ByVal usuario As String, ByVal cpf As String) As String
            Dim inValue As WsControleSenha.ValidarUsuarioCPFRequest = New WsControleSenha.ValidarUsuarioCPFRequest()
            inValue.Body = New WsControleSenha.ValidarUsuarioCPFRequestBody()
            inValue.Body.tabela = tabela
            inValue.Body.usuario = usuario
            inValue.Body.cpf = cpf
            Dim retVal As WsControleSenha.ValidarUsuarioCPFResponse = CType(Me,WsControleSenha.CriptografiaSoap).ValidarUsuarioCPF(inValue)
            Return retVal.Body.ValidarUsuarioCPFResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_alterarSenha(ByVal request As WsControleSenha.alterarSenhaRequest) As WsControleSenha.alterarSenhaResponse Implements WsControleSenha.CriptografiaSoap.alterarSenha
            Return MyBase.Channel.alterarSenha(request)
        End Function
        
        Public Function alterarSenha(ByVal novaSenha As String, ByVal tabela As String, ByVal login As String) As String
            Dim inValue As WsControleSenha.alterarSenhaRequest = New WsControleSenha.alterarSenhaRequest()
            inValue.Body = New WsControleSenha.alterarSenhaRequestBody()
            inValue.Body.novaSenha = novaSenha
            inValue.Body.tabela = tabela
            inValue.Body.login = login
            Dim retVal As WsControleSenha.alterarSenhaResponse = CType(Me,WsControleSenha.CriptografiaSoap).alterarSenha(inValue)
            Return retVal.Body.alterarSenhaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsControleSenha_CriptografiaSoap_RetornaSenhaBD(ByVal request As WsControleSenha.RetornaSenhaBDRequest) As WsControleSenha.RetornaSenhaBDResponse Implements WsControleSenha.CriptografiaSoap.RetornaSenhaBD
            Return MyBase.Channel.RetornaSenhaBD(request)
        End Function
        
        Public Function RetornaSenhaBD(ByVal schema As String, ByVal baseHomologacao As Boolean) As String
            Dim inValue As WsControleSenha.RetornaSenhaBDRequest = New WsControleSenha.RetornaSenhaBDRequest()
            inValue.Body = New WsControleSenha.RetornaSenhaBDRequestBody()
            inValue.Body.schema = schema
            inValue.Body.baseHomologacao = baseHomologacao
            Dim retVal As WsControleSenha.RetornaSenhaBDResponse = CType(Me,WsControleSenha.CriptografiaSoap).RetornaSenhaBD(inValue)
            Return retVal.Body.RetornaSenhaBDResult
        End Function
    End Class
End Namespace
